export const schools = [
  {
    id: 1,
    name: "Green Valley High",
    email: "contact@greenvalley.edu",
    role: "Admin",
    licenses: 120,
    teachers: 25,
    students: 980,
    i: 78,
    e: 84,
    c: 65,
    action: "Edit/Delete",
  },
  {
    id: 2,
    name: "Springfield Public School",
    email: "info@springfieldps.org",
    role: "Moderator",
    licenses: 80,
    teachers: 15,
    students: 760,
    i: 71,
    e: 60,
    c: 74,
    action: "Edit/Delete",
  },
  {
    id: 3,
    name: "Horizon International",
    email: "admin@horizonint.com",
    role: "Admin",
    licenses: 150,
    teachers: 30,
    students: 1200,
    i: 90,
    e: 88,
    c: 85,
    action: "Edit/Delete",
  },
  {
    id: 4,
    name: "Lakeside Academy",
    email: "hello@lakesideacademy.org",
    role: "Admin",
    licenses: 95,
    teachers: 18,
    students: 812,
    i: 65,
    e: 70,
    c: 58,
    action: "Edit/Delete",
  },
  {
    id: 5,
    name: "Oakridge School",
    email: "admin@oakridge.in",
    role: "Moderator",
    licenses: 130,
    teachers: 22,
    students: 1024,
    i: 80,
    e: 82,
    c: 75,
    action: "Edit/Delete",
  },
  {
    id: 6,
    name: "Sunrise Public School",
    email: "contact@sunrisepublic.edu",
    role: "Admin",
    licenses: 100,
    teachers: 20,
    students: 910,
    i: 77,
    e: 79,
    c: 70,
    action: "Edit/Delete",
  },
  {
    id: 7,
    name: "Bluebell High School",
    email: "bluebell@schools.com",
    role: "Moderator",
    licenses: 85,
    teachers: 16,
    students: 689,
    i: 66,
    e: 71,
    c: 62,
    action: "Edit/Delete",
  },
  {
    id: 8,
    name: "Hillview International",
    email: "info@hillviewintl.com",
    role: "Admin",
    licenses: 140,
    teachers: 28,
    students: 1100,
    i: 85,
    e: 90,
    c: 87,
    action: "Edit/Delete",
  },
  {
    id: 9,
    name: "Maple Leaf Academy",
    email: "support@mapleleaf.edu",
    role: "Moderator",
    licenses: 92,
    teachers: 19,
    students: 795,
    i: 72,
    e: 68,
    c: 64,
    action: "Edit/Delete",
  },
  {
    id: 10,
    name: "Riverdale School",
    email: "admin@riverdale.org",
    role: "Admin",
    licenses: 110,
    teachers: 21,
    students: 940,
    i: 79,
    e: 83,
    c: 76,
    action: "Edit/Delete",
  },
];

export const students = [
  {
    id: "1",
    name: "Aarav Sharma",
    contactNumber: "+91 9876543210",
    year: 1,
    section: "A",
    challenges: 5,
    inprogress: 2,
    completed: 3,
    action: "View",
  },
  {
    id: "2",
    name: "Sneha Reddy",
    contactNumber: "+91 9123456780",
    year: 2,
    section: "B",
    challenges: 4,
    inprogress: 1,
    completed: 3,
    action: "View",
  },
  {
    id: "3",
    name: "Rohan Mehta",
    contactNumber: "+91 9988776655",
    year: 3,
    section: "C",
    challenges: 6,
    inprogress: 3,
    completed: 3,
    action: "View",
  },
  {
    id: "4",
    name: "Diya Patel",
    contactNumber: "+91 9871234567",
    year: 4,
    section: "A",
    challenges: 8,
    inprogress: 4,
    completed: 4,
    action: "View",
  },
  {
    id: "5",
    name: "Krishna Nair",
    contactNumber: "+91 9012345678",
    year: 1,
    section: "B",
    challenges: 3,
    inprogress: 1,
    completed: 2,
    action: "View",
  },
  {
    id: "6",
    name: "Meera Joshi",
    contactNumber: "+91 9765432109",
    year: 2,
    section: "C",
    challenges: 7,
    inprogress: 5,
    completed: 2,
    action: "View",
  },
  {
    id: "7",
    name: "Aditya Verma",
    contactNumber: "+91 9823456712",
    year: 3,
    section: "A",
    challenges: 4,
    inprogress: 2,
    completed: 2,
    action: "View",
  },
  {
    id: "8",
    name: "Ananya Iyer",
    contactNumber: "+91 9956784321",
    year: 4,
    section: "B",
    challenges: 6,
    inprogress: 1,
    completed: 5,
    action: "View",
  },
  {
    id: "9",
    name: "Yash Desai",
    contactNumber: "+91 9870098765",
    year: 1,
    section: "C",
    challenges: 5,
    inprogress: 0,
    completed: 5,
    action: "View",
  },
  {
    id: "10",
    name: "Pooja Singh",
    contactNumber: "+91 9898989898",
    year: 2,
    section: "A",
    challenges: 9,
    inprogress: 6,
    completed: 3,
    action: "View",
  },
];
